site_name:        NextGenSeqUtils.jl
repo_url:         https://github.com/MurrrellGroup/NextGenSeqUtils.jl
site_description: A package with utilities for next generation sequencing
site_author:      Ben Murrell

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - Align: align.md
  - hmm: hmm.md
  - io: io.md
  - kmers: kmers.md
  - orient: orient.md
  - paths: paths.md
  - phreds: phreds.md
  - simulation: simulation.md
  - utils: utils.md

